export const metadata = {
    title: 'Api test',
    description: 'Generated by create next app',
}

export default function PostsLayout({
    children
}) {
    return (
        <div>
            <p>PostsLayout</p>
            {children}
        </div>
    )
}
